question 1 


In [3]:
import numpy as np
array = np.arange(6)
print("type ",array.dtype)
print(array)

type  int32
[0 1 2 3 4 5]


Question 2 

In [7]:
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == 'float64':
    print("yes")

yes


Question 3 

In [8]:
import numpy as np
arr = np.array([1+2j, 2-3j, 3+4j], dtype=np.complex128)
print(arr)

[1.+2.j 2.-3.j 3.+4.j]


Question 4


In [10]:
array = np.arange(6)
print(array , array.dtype)
array = array.astype(np.float32)
print(array , array.dtype)

[0 1 2 3 4 5] int32
[0. 1. 2. 3. 4. 5.] float32


Question 5

In [11]:
import numpy as np
arr = np.array([1.123456789, 2.987654321, 3.141592653])
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print("Data type:", arr_float32.dtype)

[1.1234568 2.9876542 3.1415927]
Data type: float32


Question 6

In [12]:
import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int32


Question 7

In [15]:
def array_dimension(arr):
    dim = arr.ndim
    return dim
arr = np.arange(20)
print("dimension of array",array_dimension(arr))

dimension of array 1


Question 8

In [14]:
def  item_size_info(arr):
    item_size = arr.itemsize
    arr_size = arr.nbytes
    return item_size , arr_size

arr = np.arange(9)
elem_size , arr_size = item_size_info(arr)
print("element size : ",elem_size)
print("arr_size : " , arr_size)

element size :  4
arr_size :  36


Question 9

In [17]:
import numpy as np

def array_strides(arr):
    strides = arr.strides
    return strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)

Strides: (12, 4)


Question 10

In [18]:

import numpy as np

def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (12, 4)


Question 11

In [21]:

def create_zeros_array(n):
    return np.zeros(n)

create_zeros_array(5)

array([0., 0., 0., 0., 0.])

Question 12

In [22]:
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))
create_ones_matrix(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Question 13

In [23]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print(range_array)

[0 2 4 6 8]


quesiton 14

In [26]:
def generate_linear_space(start ,stop , num):
    return np.linspace(start,stop,num)
start = 0.0
stop = 10.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print(linear_space)

[ 0.   2.5  5.   7.5 10. ]


Question 15

In [27]:
def create_identity_matrix(n):
    return np.eye(n)
n = 4
create_identity_matrix(n)
    

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Question 16

In [28]:
def convert_array(lst):
    return np.array(lst)
lst = [1,2,3,4,54,5,6,67]
print(convert_array(lst))

[ 1  2  3  4 54  5  6 67]


Question 17


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
print("Original array:", arr)
print("Viewed array:", arr_view)

Original array: [1 2 3 4 5]
Viewed array: [1 2 3 4 5]


Question 18

In [31]:
def concatenate_function(arr1 , arr2):
    return np.concatenate((arr1,arr2) , axis = 0)#rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenate_function(arr1 , arr2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
#question 19
def concatenate_numpy_array(arr1 , arr2):
    return np.concatenate((arr1,arr2) , axis = 1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])
concatenate_numpy_array(arr1,arr2)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [35]:
#question 20
def vertical_stack(arrays):
    return np.vstack(arrays)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])
arrays = [arr1,arr2,arr3]
vertical_stack(arrays)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
#question 21
def create_array(start,end,step):
    return np.arange(start,end+1,step)
start = 1
end = 10
step = 2
array = create_array(start, end, step)
print(array)

[1 3 5 7 9]


In [38]:
#question 22
def Equal_space():
    return np.linspace(0,1,10)
array = Equal_space()
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [39]:
#question 23
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(np.log10(1), np.log10(1000), 5)
array = generate_logarithmically_spaced_values()
print(array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [41]:
#question 24
import numpy as np
import pandas as pd


data = np.random.randint(1, 101, size=(5, 3))


df = pd.DataFrame(data, columns=['A', 'B', 'C'])

print(df)

    A   B   C
0  57  27  90
1   2  42  84
2  39  70  90
3  75  86  15
4  41  14  92


In [43]:
#question 25
def replace_negative(df,column):
    df[column] = np.where(df[column]<0 , 0 , df[column])
    return df
df = pd.DataFrame({'A': [-1, 2, -3, 4], 'B': [5, -6, 7, -8]})
print(replace_negative(df, 'A'))
    
    

   A  B
0  0  5
1  2 -6
2  0  7
3  4 -8


In [44]:
#question 26
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [47]:
#question 27
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr_2d[1,2])

6


In [48]:
#question 28
arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])

[ 8 10  7]


In [53]:
#question 29
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])

[3 4 5 6]


In [54]:
#question 30
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[0:2,1:3])

[[2 3]
 [5 6]]


In [55]:
#question 31
def extract_elements(arr, indices):
    return np.take(arr, indices)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([1, 3, 5])
print(extract_elements(arr, indices))  

[2 4 6]


In [56]:
#question 32
import numpy as np
def filter_elements(arr, threshold):
    return arr[arr > threshold]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5
print(filter_elements(arr, threshold)) 

[6 7 8 9]


In [60]:
#question 33
import numpy as np

def extract_elements(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]
arr = np.random.rand(3, 4, 5)
idx1 = np.array([0, 2])
idx2 = np.array([1, 3])
idx3 = np.array([0, 2])
print(extract_elements(arr, idx1, idx2, idx3))

[0.99595273 0.19672031]


In [61]:
#question 34
import numpy as np
def filter_elements(arr, cond1, cond2):
    return arr[(cond1) & (cond2)]
    
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
cond1 = arr > 3
cond2 = arr % 2 == 0
print(filter_elements(arr, cond1, cond2))

[4 6 8]


In [62]:
#question 35
import numpy as np

def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])
print(extract_elements(arr, row_indices, col_indices)) 

[2 9]


In [63]:
#question 36

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(arr)

arr += 5

print("Array after adding 5:")
print(arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [1]:
#question 37
import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 

result = arr1.T * arr2

print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [2]:
#question 38
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 
result = arr2 + arr1.T

print(result)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [7]:
#question 39
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([1,2,3])
#adding using numpy broadcasting 
result = arr1 + arr2.T
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [14]:
#question 40
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)

arr2 = arr2[:, :, np.newaxis]

result = arr1 * arr2

print(result)

[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [17]:
#question 41
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(arr , axis = 0)
print(mean)

[2.5 3.5 4.5]


In [19]:
#question 42
arr = np.array([[1, 2, 3], [4, 5, 6]])
max = np.max(arr , axis = 1)
print(max)

[3 6]


In [20]:
#question 43
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr , axis = 1))

[2 2]


In [21]:
#question 44

arr = np.array([[1, 2, 3], [4, 5, 6]])
#defining function 
def moving_sum(a, window_size):
    return np.convolve(a, np.ones(window_size), mode='valid')

# main
result = np.apply_along_axis(moving_sum, 1, arr, window_size=2)

print(result)

[[ 3.  5.]
 [ 9. 11.]]


In [23]:
#question 45
arr = np.array([[2, 4, 6], [3, 5, 7]])
result  = np.all(arr%2 == 0 , axis = 0)
print(result)

[False False False]


In [25]:
#question 46
original_array = np.array([1, 2, 3, 4, 5, 6])
reshped_array = original_array.reshape(2,3)
reshped_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#question 47
#defining the function 
def flatten(matrix):
    return matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatten(input_matrix))

[1 2 3 4 5 6]


In [31]:
#question 48
def array_row_concate(arr1,arr2 ):
    return np.concatenate((arr1,arr2) , axis =1)
    
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
array_row_concate(array1,array2)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [33]:
#question 49
def split_array(array, axis, num_subarrays):
    return np.split(array, num_subarrays, axis=axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_array(original_array ,1,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [36]:
#question 50
def update(array , insert_indices,delete_indices , insert_values):
    #inserting the element
    array = np.insert(array , insert_indices ,insert_values)
    #deleting  the element 
    array = np.delete(array , delete_indices)
    return array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
update(original_array , indices_to_insert ,indices_to_delete,values_to_insert)

array([ 1, 10,  4, 11,  5])

In [41]:
#question 51
arr1 = np.random.randint(0,10,size = (10))
print("arr`1:",arr1)
arr2 = np.arange(1,11)
print("arr2" , arr2)
result = arr1 + arr2
result

arr`1: [5 7 7 4 6 5 0 8 1 6]
arr2 [ 1  2  3  4  5  6  7  8  9 10]


array([ 6,  9, 10,  8, 11, 11,  7, 16, 10, 16])

In [42]:
#question 52
arr1 = np.arange(11,1,-1)
print("arr`1:",arr1)
arr2 = np.arange(1,11)
print("arr2" , arr2)
result = arr1-arr2
result

arr`1: [11 10  9  8  7  6  5  4  3  2]
arr2 [ 1  2  3  4  5  6  7  8  9 10]


array([10,  8,  6,  4,  2,  0, -2, -4, -6, -8])

In [43]:
#question 54
arr1 = np.arange(2, 12, 2)
print("Array 1:", arr1)
arr2 = np.arange(1, 6)
print("Array 2:", arr2)

# Perform element-wise division
result = arr1 / arr2
print("Result:", result)

Array 1: [ 2  4  6  8 10]
Array 2: [1 2 3 4 5]
Result: [2. 2. 2. 2. 2.]


In [44]:
#question 55
import numpy as np


arr1 = np.arange(1, 6)
print("Array 1:", arr1)
arr2 = np.flip(arr1)
print("Array 2:", arr2)

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = arr1 ** arr2
print("Result:", result)

Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Result: [ 1 16 27 16  5]


In [45]:
#question 56
def count_substring(arr, substring):
    return np.count_nonzero(np.core.defchararray.find(arr, substring) != -1)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
print(count_substring(arr, substring))

3


In [49]:
#question 57
def extract_upper(arr):
    return np.array([ch for i in arr for ch in i if ch.isupper()]) 
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_upper(arr))

['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [50]:
#question 58
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old = "gr"
new = "W"
replace_substring(arr,old,new)

array(['apple', 'banana', 'Wape', 'pineapple'], dtype='<U9')

In [52]:
#question 59
def concat_strings(arr1, arr2):
    return np.char.add(arr1, arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concat_strings(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [56]:
#question 60
def longest_string(arr):
    return np.max([len(s) for s in arr])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_string(arr)

9

In [58]:
#question 61
data = np.random.randint(1,1000,size = (101))
print("mean : ",np.mean(data))
print("variance : ",np.var(data))
print("median : " , np.median(data))


mean :  472.0990099009901
variance :  80302.50504852468
median :  453.0


In [59]:
#question 62

arr = np.random.randint(1, 101, size=50)

p25 = np.percentile(arr, 25)
p75 = np.percentile(arr, 75)

print("25th percentile:", p25)
print("75th percentile:", p75)

25th percentile: 27.5
75th percentile: 73.75


In [60]:
#question 63
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 3, 4, 5, 6])

# Compute the correlation coefficient between the arrays
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.9999999999999999


In [61]:
#question 64
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using NumPy's dot function
result = np.dot(matrix1, matrix2)

print("Result:")
print(result)

Result:
[[19 22]
 [43 50]]


In [62]:
#question 65
import numpy as np

# Create an array of 50 integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)

# Calculate the first and third quartiles (25th and 75th percentiles)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)

print("10th percentile:", p10)
print("50th percentile (median):", p50)
print("90th percentile:", p90)
print("First quartile (25th percentile):", q1)
print("Third quartile (75th percentile):", q3)


10th percentile: 98.6
50th percentile (median): 437.5
90th percentile: 871.7
First quartile (25th percentile): 157.25
Third quartile (75th percentile): 787.5


In [63]:
#question 66
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)

print("Index of 30:", index)

Index of 30: (array([2], dtype=int64),)


In [64]:
#question 67
arr = np.random.randint(1,10 ,size = (6))
arr_sort = np.sort(arr)
print("arr", arr)
print("arr_sorted" ,arr_sort)

arr [5 9 8 6 2 9]
arr_sorted [2 5 6 8 9 9]


In [65]:
#question 68
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]

print(filtered_arr)

[25 42 30]


In [67]:
#question 69
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr%3 == 0]
filtered_arr


array([12, 15])

In [72]:
#question 70
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr>=20) & (arr<=40)]
filtered_arr

array([20, 30, 40])

In [73]:
#question 71
import numpy as np

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print(byte_order)

=


In [74]:
#question 72
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)

# Perform byte swapping in place
arr.byteswap(inplace=True)

print("Array after byte swapping:")
print(arr)

Original array:
[1 2 3]
Array after byte swapping:
[16777216 33554432 50331648]


In [75]:
#question 73
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

print("Array with swapped byte order:")
print(swapped_arr)

Original array:
[1 2 3]
Array with swapped byte order:
[16777216 33554432 50331648]


In [76]:
#question 74
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)
# Swap byte order conditionally based on system endianness
if sys.byteorder == 'little':
    swapped_arr = arr.newbyteorder('>')
elif sys.byteorder == 'big':
    swapped_arr = arr.newbyteorder('<')
else:
    raise ValueError("Unsupported system endianness")

print("Array with swapped byte order (if necessary):")
print(swapped_arr)

Original array:
[1 2 3]
Array with swapped byte order (if necessary):
[16777216 33554432 50331648]


In [78]:
#question 75
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

print("Array dtype byteorder:", arr.dtype.byteorder)
print("System byteorder:", sys.byteorder)

if arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary")
else:
    print("Byte swapping is not necessary")

Array dtype byteorder: =
System byteorder: little
Byte swapping is necessary


In [79]:
# Question 76

# Create a NumPy array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)
print("Original array arr1:")
print(arr1)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()
print("\nCopy of arr1 named copy_arr:")
print(copy_arr)

# Modify an element in copy_arr
copy_arr[0] = 100
print("\nModified copy_arr:")
print(copy_arr)

# Check if modifying copy_arr affects arr1
print("\nOriginal array arr1 after modifying copy_arr:")
print(arr1)

Original array arr1:
[ 1  2  3  4  5  6  7  8  9 10]

Copy of arr1 named copy_arr:
[ 1  2  3  4  5  6  7  8  9 10]

Modified copy_arr:
[100   2   3   4   5   6   7   8   9  10]

Original array arr1 after modifying copy_arr:
[ 1  2  3  4  5  6  7  8  9 10]


In [81]:
#Question 77
import numpy as np

# Create a 2D NumPy array 'matrix' of shape (3, 3) with random integers
matrix = np.random.randint(0, 10, size=(3, 3))
print("Original matrix:")
print(matrix)

# Extract a slice 'view_slice' from the matrix
view_slice = matrix[:2, :2]
print("\nSlice 'view_slice' from the matrix:")
print(view_slice)

# Modify an element in 'view_slice'
view_slice[0, 0] = 100
print("\nModified 'view_slice':")
print(view_slice)

# Observe if modifying 'view_slice' changes the original 'matrix'
print("\nOriginal matrix after modifying 'view_slice':")
print(matrix)
print("it does affect the original array")

Original matrix:
[[3 8 2]
 [5 8 7]
 [2 5 2]]

Slice 'view_slice' from the matrix:
[[3 8]
 [5 8]]

Modified 'view_slice':
[[100   8]
 [  5   8]]

Original matrix after modifying 'view_slice':
[[100   8   2]
 [  5   8   7]
 [  2   5   2]]
it does affect the original array


In [82]:
#question 78
import numpy as np

# Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)
print("Original array 'array_a':")
print(array_a)

# Extract a slice 'view_b' from 'array_a'
view_b = array_a[:2, :2]
print("\nSlice 'view_b' from 'array_a':")
print(view_b)

# Broadcast the addition of 5 to 'view_b'
view_b += 5
print("\n'view_b' after broadcasting addition of 5:")
print(view_b)

# Check if it alters the original 'array_a'
print("\nOriginal 'array_a' after broadcasting addition of 5 to 'view_b':")
print(array_a)

Original array 'array_a':
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice 'view_b' from 'array_a':
[[1 2]
 [4 5]]

'view_b' after broadcasting addition of 5:
[[ 6  7]
 [ 9 10]]

Original 'array_a' after broadcasting addition of 5 to 'view_b':
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [83]:
#question 79
import numpy as np

# Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)
print("Original array 'orig_array':")
print(orig_array)

# Create a reshaped view 'reshaped_view' of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view 'reshaped_view':")
print(reshaped_view)

# Modify an element in 'reshaped_view'
reshaped_view[0, 0] = 100
print("\nModified 'reshaped_view':")
print(reshaped_view)

# Check if it reflects changes in the original 'orig_array'
print("\nOriginal 'orig_array' after modifying 'reshaped_view':")
print(orig_array)

Original array 'orig_array':
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view 'reshaped_view':
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified 'reshaped_view':
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original 'orig_array' after modifying 'reshaped_view':
[[100   2   3   4]
 [  5   6   7   8]]


In [84]:
#question 80
import numpy as np

# Create a NumPy array 'data' of shape (3, 4) with random integers
data = np.random.randint(0, 10, size=(3, 4))
print("Original array 'data':")
print(data)

# Extract a copy 'data_copy' of elements greater than 5
data_copy = data[data > 5].copy()
print("\nCopy 'data_copy' of elements greater than 5:")
print(data_copy)

# Modify an element in 'data_copy'
data_copy[0] = 100
print("\nModified 'data_copy':")
print(data_copy)

# Verify if it affects the original 'data'
print("\nOriginal 'data' after modifying 'data_copy':")
print(data)

Original array 'data':
[[9 8 5 1]
 [0 8 5 4]
 [9 7 8 3]]

Copy 'data_copy' of elements greater than 5:
[9 8 8 9 7 8]

Modified 'data_copy':
[100   8   8   9   7   8]

Original 'data' after modifying 'data_copy':
[[9 8 5 1]
 [0 8 5 4]
 [9 7 8 3]]


In [85]:
# Question 81
import numpy as np

# Create two matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 3, 4], [5, 6, 7]])

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

# Perform addition between A and B
addition_result = A + B
print("Addition result:")
print(addition_result)

# Perform subtraction between A and B
subtraction_result = A - B
print("Subtraction result:")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[2 3 4]
 [5 6 7]]
Addition result:
[[ 3  5  7]
 [ 9 11 13]]
Subtraction result:
[[-1 -1 -1]
 [-1 -1 -1]]


In [86]:
#question 82
# Generate two matrices C (3x2) and D (2x4)
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Matrix C:")
print(C)
print("Matrix D:")
print(D)

# Perform matrix multiplication between C and D
result = np.matmul(C, D)
print("Matrix multiplication result:")
print(result)

Matrix C:
[[1 2]
 [3 4]
 [5 6]]
Matrix D:
[[1 2 3 4]
 [5 6 7 8]]
Matrix multiplication result:
[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]


In [87]:
#question 83
import numpy as np

# Create a matrix E
E = np.array([[1, 2, 3], [4, 5, 6]])

print("Matrix E:")
print(E)

# Find the transpose of matrix E
E_transpose = E.T

print("Transpose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]]
Transpose of Matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [88]:
#question 84
import numpy as np

# Generate a square matrix F
F = np.array([[2, 4], [6, 8]])

print("Matrix F:")
print(F)

# Compute the determinant of matrix F
det_F = np.linalg.det(F)

print("Determinant of Matrix F:")
print(det_F)

Matrix F:
[[2 4]
 [6 8]]
Determinant of Matrix F:
-8.000000000000002


In [89]:
#question 85
# Create a square matrix G
G = np.array([[4, 7], [2, 6]])

print("Matrix G:")
print(G)

# Find the inverse of matrix G
G_inv = np.linalg.inv(G)

print("Inverse of Matrix G:")
print(G_inv)

Matrix G:
[[4 7]
 [2 6]]
Inverse of Matrix G:
[[ 0.6 -0.7]
 [-0.2  0.4]]
